sudo: false
language: perl
perl:
  - "blead" # allow failure on blead but this could help detect regression from p5p
  - "5.28"
  - "5.26"
  - "5.24"
  - "5.22"

before_install:
  - cpanm --notest App::ModuleBuildTiny Test2::Harness

script:
  yath test -T -j4 --verbose

notifications:
  irc:
    channels:
      - "irc.freenode.org#chupei.pm"
    use_notice: true
